sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with Dockerfile"
  - docker build -t alsgks1218/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alsgks1218/docker-react npm run test -- --coverage

after_success:
  - echo "Test Success"

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-455213246709"
  bucket_path: "docker-react-app"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
